name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make daily contribution
        run: |
          echo "Making daily contribution"
          echo "$(date)" >> utils.md  # Cambiado para añadir la fecha en utils.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Daily contribution"
          add: "utils.md"  # Cambiado para hacer commit de utils.md

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: daily-contribution
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Daily Contribution"
          commit-message: "Daily contribution"
          branch: daily-contribution
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
